name: ✨ Feature Request
description: Suggest a new feature for this project
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees:
  - HARIOM-JHA01

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Must have)
        - High (Important)
        - Medium (Nice to have)
        - Low (Optional)
    validations:
      required: true

  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected Areas
      description: Which parts of the application would this feature affect?
      options:
        - label: Authentication
        - label: Product Management
        - label: Shopping Cart
        - label: Checkout
        - label: Orders
        - label: Search
        - label: Admin Dashboard
        - label: User Account
        - label: Performance
        - label: UI/UX
        - label: Other

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Paste images or links here

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
